# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'orbitingapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for orbitingapp
  pod 'Firebase/Core', '~> 4.13'
  pod 'Firebase/Messaging'

  pod 'react-native-wkwebview', :path => '../node_modules/react-native-wkwebview-reborn'

end
