# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :staging do
    increment_build_number
    match(
      type: "appstore",
      git_url: "https://github.com/orbiting/app-certificates"
    ) # more information: https://codesigning.guide
    build_app(workspace: "republikapp.xcworkspace", scheme: "republikapp (staging)", export_xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
    lane :production do
    increment_build_number
    match(
      type: "appstore",
      git_url: "https://github.com/orbiting/app-certificates"
    ) # more information: https://codesigning.guide
    build_app(workspace: "republikapp.xcworkspace", scheme: "republikapp (production)")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    #upload_to_app_store 
  end
end
