# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    match(
      type: "appstore",
      git_url: "git@github.com:orbiting/app-certificates.git"
    ) # more information: https://codesigning.guide
    gym(
      scheme: "orbitingapp (staging)"
    ) # Build your app - more options available
    pilot(skip_waiting_for_build_processing: true)
    slack(
     message: "New beta version successfully uploaded to the Apple TestFlight.",
     success: true,
     slack_url: ENV["SLACK_URL"],
     attachment_properties: {
       fields: [
         {
           title: "Build code",
           value: lane_context[SharedValues::BUILD_NUMBER],
         },
       ]
     }
   )
  end
end
