# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
fastlane_require 'dotenv'

platform :android do
  desc "Deploy a new alpha version to the Google Play Store"
  lane :alpha do |options|
    increment_version_code(
      app_project_dir: "./app"
    )
    increment_version_name(
      bump_type: options[:type] || 'patch',
      app_project_dir: "./app"
    )
    gradle(
      task: "assemble",
      build_type: "stagingRelease"
    )
    supply(
      track: "alpha",
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
    slack(
     message: "New alpha version successfully uploaded to the GooglePlay store.",
     success: true,
     slack_url: ENV["SLACK_URL"],
     attachment_properties: {
       fields: [
         {
           title: "Build version",
           value: lane_context[SharedValues::VERSION_NAME],
         },
         {
           title: "Build code",
           value: lane_context[SharedValues::VERSION_CODE],
         },
       ]
     }
   )
  end

  lane :test do |options|

  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
