# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
fastlane_require 'dotenv'

platform :android do
  desc "Deploy a new alpha version to the Google Play Store"
  lane :staging do |options|
    increment_version_code(
      app_project_dir: "./app"
    )
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    supply(
      track: "alpha",
      aab: "#{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
    )
  end

  lane :production do |options|
    increment_version_code(
      app_project_dir: "./app"
    )
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    supply(
      track: "alpha",
      aab: "#{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
    )
  end
end